#dependabot configuration for NPM

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    open-pull-requests-limit: 10
    schedule:
      interval: "weekly"
    groups:
      emotion:
        patterns:
          - "@emotion*"
      mui:
        patterns:
          - "@mui*"
      gatsby:
        patterns:
          - "gatsby*"
      lint:
        patterns:
          - "eslint*"
          - "@eslint*"
          - "globals"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
