name: Update Browserslist

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 5'

jobs:
  browserslist:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Update npm
        run: |
          npm i -g npm@latest

      - name: Update Browserslist
        run: |
          npm run browserslist

      - name: Commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet --cached HEAD || git commit -m "Update Browserslist"

      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
