name: Cypress

on:
  workflow_dispatch:
  pull_request_review:
    branches:
      - src

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    if: github.actor != 'dependabot[bot]'

    steps:
      - uses: actions/checkout@v2

      - name: Cypress
        uses: cypress-io/github-action@v2
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_GITHUB_TOKEN }}
        with:
          build: npm run build
          start: npm run serve
          wait-on: 'http://localhost:8000'
